### ISSUE TITLE
Way to report warnings and errors for calibration samples.

### ISSUE THREAD

**Issue by damellis** [damellis/ESP#138]
The example author should have a way to warn the user if a calibration sample seems problematic (e.g. lots of noise) or simply won't work at all (e.g. not enough data to perform the required computations). These should appear in the GUI, with the calibration sample not saved if an error is reported.

**Comment by nebgnahz** [comment]
Related: https://github.com/damellis/sensors/issues/88

We need a way (small side panel for error reporting).

**Comment by nebgnahz** [comment]
GUI part is easy, APIs for example authors are hard.

The current plan will be modifying the `CalibratorCallback` function signature such that the return value could either be success or failure with an error message.

**Comment by nebgnahz** [comment]
Half-done with https://github.com/damellis/ESP/pull/217
Needs GUI support next.

**Comment by nebgnahz** [comment]
Now GUI shows custom error message during calibration.

See commit https://github.com/damellis/ESP/commit/4144375e9be26d7fa23b69276bb638b4ca6faae2.
