### ISSUE TITLE
Write up overview of how to create an ESP example.

### ISSUE THREAD

**Issue by damellis** [damellis/ESP#170]
This would point to the individual API docs, #169, but would provide a more high-level discussion / overview.

**Comment by nebgnahz** [comment]
Meanwhile, our Doxygen online documentation contains examples.

For example, [Gesture detection using accelerometers](http://damellis.github.io/ESP/user_accelerometer_gestures_8cpp-example.html).

**Comment by nebgnahz** [comment]
I believe this should be considered as "done" with [this blog](https://create.arduino.cc/projecthub/mellis/gesture-recognition-using-accelerometer-and-esp-mac-only-71faa1) and our [wiki](https://github.com/damellis/ESP/wiki).
