### ISSUE TITLE
Tutorial for audio recognition (of relatively stable-pitched sounds).

### ISSUE THREAD

**Issue by damellis** [damellis/ESP#188]
e.g. dial tones, piano notes, etc.

**Comment by nebgnahz** [comment]
Created initial skeleton here (https://github.com/damellis/ESP/wiki/%5BExample%5D-Simple-Audio-Detection). Will work on refining it.

**Comment by nebgnahz** [comment]
[Simple Audio Detection](https://github.com/damellis/ESP/wiki/%5BExample%5D-Simple-Audio-Detection) is in a reasonably good shape.
