### ISSUE TITLE
Can't adjust first tunable parameter after serial port selection list goes away.

### ISSUE THREAD

**Issue by damellis** [damellis/ESP#190]
It looks like once I select a serial port, I can no longer change the value of the first tunable parameter.

**Comment by nebgnahz** [comment]
Using `setVisibility(false)` doesn't seem to remove the component (https://github.com/braitsch/ofxDatGui/issues/73), hence first parameter is not tuneable from the GUI.

**Comment by nebgnahz** [comment]
Stephen Braitsch has fixed this upstream. Sync-ing with the remote branch (08ad5a547168f69afde7cc7675a706ab20a2f44a) works.
