### ISSUE TITLE
Way to reset / clear all training data.

### ISSUE THREAD

**Issue by damellis** [damellis/ESP#224]
Reset the example.

**Comment by nebgnahz** [comment]
`All samples within a label` or `all samples in all labels`?
The TrainingDataManager will support both. But which one do we want?

**Comment by damellis** [comment]
@audalogy: any suggestions?

**Comment by nebgnahz** [comment]
APIs provided with https://github.com/damellis/ESP/commit/c543fdb0a88f9aa2fa5103b564788f2ffbb903e3.

We need to decide the desired behavior.

**Comment by damellis** [comment]
In our meeting, we decided to add a "delete all" button for each class. If the user wants to delete all samples in all classes, they only need to click the "delete all" button once for each class, which doesn't seem too bad.
