### ISSUE TITLE
Use non-red color for "select serial port" menu.

### ISSUE THREAD

**Issue by damellis** [damellis/ESP#232]
The red seems to imply some sort of error.

**Comment by nebgnahz** [comment]
Green probably works better (https://github.com/damellis/ESP/commit/3555b5377f5dc3d8b60747d899062296811bfdb7)

If not, we can simply change this line: https://github.com/damellis/ESP/blob/3555b5377f5dc3d8b60747d899062296811bfdb7/Xcode/ESP/src/ofApp.cpp#L36
