### ISSUE TITLE
Factor out a training data manager.

### ISSUE THREAD

**Issue by damellis** [damellis/ESP#238]
That can talk to the GUI in ofApp.

**Comment by damellis** [comment]
It seems like it would be good if this manager didn't depend on openFrameworks. Think that makes sense / is possible?

**Comment by nebgnahz** [comment]
PR https://github.com/damellis/ESP/pull/247 has it. It doesn't depend on openFrameworks at all.

There is also a standalone unit test for the manager.

The program will crash if invalid index is provided (new issue: https://github.com/damellis/ESP/issues/248)

**Comment by nebgnahz** [comment]
The manager is more or less considered done after https://github.com/damellis/ESP/commit/0c96ec094edf17b852aaceb53b82365d4af16051.
