### ISSUE TITLE
Need to tell runUnitTests how to find libgrt.dylib (OS X).

### ISSUE THREAD

**Issue by damellis** [damellis/ESP#250]
I get the following error when running runUnitTests:

```
dyld: Library not loaded: @executable_path/../Frameworks/libgrt.dylib
  Referenced from: /Users/mellis/Source/ESP/./runUnitTests
  Reason: image not found
Trace/BPT trap: 5
```

It looks like this can be fixed by telling runUnitTests where to find libgrt.dylib:

```
install_name_tool -change @executable_path/../Frameworks/libgrt.dylib Xcode/ESP/libgrt.dylib runUnitTests
```

But I'm not sure how to tell cmake to insert this into the Makefile. @nebgnahz: any ideas?

**Comment by nebgnahz** [comment]
Fixed.

**Comment by nebgnahz** [comment]
The idea is to run a custom command (`install_name_tool`) after build (see `POST_BUILD` argument).

Although I am not sure how the path `../Framework/libgrt.dylib` is added to the build process...

**Comment by damellis** [comment]
Thanks! It seems to work now. The ../Framework/libgrt.dylib is something I've been doing manually, although I recently added it to the https://github.com/damellis/ESP/blob/master/update-xcode-grt.sh script. It's needed for the ESP executables built with Xcode to find the grt.
