### ISSUE TITLE
Show serial port selection menu for other serial stream types.

### ISSUE THREAD

**Issue by damellis** [damellis/ESP#262]
e.g. FirmataStream and the sub-classes of BaseSerialStream, not just the ASCIISerialStream.

**Comment by nebgnahz** [comment]
For now, it's hardcoded in https://github.com/damellis/ESP/blob/master/Xcode/ESP/src/ofApp.cpp#L330.

Consider checking for the base class: https://github.com/damellis/ESP/blob/master/Xcode/ESP/src/istream.h#L128.

**Comment by damellis** [comment]
This may or may not depend on #277.
