### ISSUE TITLE
Don't allow spaces in class names in calibration save files.

### ISSUE THREAD

**Issue by damellis** [damellis/ESP#274]
If there's a space in the name of a CalibrateProcess, it will be written to the saved file (as the name of a class) but then we'll get an error when loading that file.

**Comment by nebgnahz** [comment]
See https://github.com/damellis/ESP/commit/d535da4f27f4375fd196813686f24e8be6717c24.

The `encodeName` and `decodeName` can be used in other scenarios when we want to avoid spaces.
