### ISSUE TITLE
Documentation Request - Touché circuit photo

### ISSUE THREAD

**Issue by narner** [damellis/ESP#313]
Would it be possible to include a photo of the Touché circuit, in addition to the schematic in the [Wiki](https://github.com/damellis/ESP/wiki/%5BExample%5D-Touch%C3%A9-swept-frequency-capacitive-sensing)? It would be helpful to reference just to make sure I'm reading the schematic correctly. 

Thank you!

**Comment by narner** [comment]
Saw an image as added in the [Wiki](https://github.com/damellis/ESP/wiki/%5BExample%5D-Touch%C3%A9-swept-frequency-capacitive-sensing), thank you! Parts came in for the circuit; looking forward to experimenting :)

**Comment by damellis** [comment]
Great, let us know how it goes!
