### ISSUE TITLE
While renaming or relabeling, pressing "esc" should cancel action, not exit.

### ISSUE THREAD

**Issue by damellis** [damellis/ESP#321]

**Comment by damellis** [comment]
When I tried this, it seems like during rename, "esc" doesn't exit but it doesn't cancel the rename either. @nebgnahz: can you look into making esc cancel the rename (restoring the previous name)?

**Comment by damellis** [comment]
Also, it appears that clicking the mouse ends the rename (i.e. the flashing cursor disappears) but it seems that future keystrokes are still used for renaming (i.e. appended to the class label/name).

**Comment by nebgnahz** [comment]
The commits are mostly small fixes and I've individually tested them. Closing for now.
