### ISSUE TITLE
Disable keyboard input while configuration menu is open.

### ISSUE THREAD

**Issue by damellis** [damellis/ESP#345]
It's possible to type into the ofxDatGui slider values, but when doing so, keys presses also trigger recording of training data, etc.

**Comment by damellis** [comment]
Related to #347.

**Comment by nebgnahz** [comment]
This is fixed per #347.

Note: you can still exit the GUI by pressing `ESC`. I am not sure if the intended behavior of ESC here should be "close the configuration panel".

**Comment by damellis** [comment]
ESC should close the configuration panel, not the application.
