### ISSUE TITLE
ESP Build for Mac OS Sierra (Qt Dependencies)

### ISSUE THREAD

**Issue by damellis** [damellis/ESP#381]
Mac OS Sierra (10.12) removes support for the QtKit that's needed by these files (resulting in the error `QuickTime/QuickTime.h: file not found`). We don't actually need those files for ESP, though, so we should remove them from the openFrameworks project, e.g. by munging the file in setup.sh.

**Comment by damellis** [comment]
It looks like we can simply remove any line with "ofQt".

**Comment by nebgnahz** [comment]
Re-opening and updated the title to track Mac OS Sierra build errors.

CMake build fails because in Mac OS Sierra. Error message:

```
ESP/third-party/openFrameworks/libs/openFrameworks/utils/ofConstants.h:66:14: fatal error: 'TargetConditionals.h' file not found
    #include <TargetConditionals.h>
             ^
1 error generated.
```
