### ISSUE TITLE
Changing baud rate of the serial port

### ISSUE THREAD

**Issue by MiladAlshomary** [damellis/ESP#399]
Hello,

Currently the ESP software reads serial ports on a baud rate  115200. How could I change this rate? Because my Lilypad XBee doesn't support this rate.

Thanks for help!

**Comment by damellis** [comment]
You can try running ESP using the Processing mode: https://github.com/damellis/processing-esp-mode

This will allow you to view and edit the code for the examples, including the serial baud rate.

**Comment by MiladAlshomary** [comment]
@damellis 

Thanks for your reply, I didn't find any installation instructions for the processing-esp-mode on Linux. Is there anyway to get it running on Linux? However I was able to run processing software on my Linux but couldn't link it with the processing-esp-mode.

Any help would be appreciated!

**Comment by nebgnahz** [comment]
@MiladAlshomary If you are using the released binaries, there is no way to change the baud rate. The baud rate is unfortunately [hard-coded](https://github.com/damellis/ESP/blob/master/Xcode/ESP/src/examples/user_accelerometer_gestures.cpp#L6).

Other than using the Processing mode, you may try directly compile and run the project (see [instructions for developers](https://github.com/damellis/ESP/blob/master/README.md#installation-for-developers)).

**Comment by MiladAlshomary** [comment]
Hey,
Yes I had to change the baud rate in the code and re build the project.

Thanks for your update

**Comment by nebgnahz** [comment]
Closing for now.
