### ISSUE TITLE
installation issue - 3rd party reference

### ISSUE THREAD

**Issue by gogela** [damellis/ESP#403]
When cloning the repository:
`git clone --recursive https://github.com/damellis/ESP.g`it
it fails with:
```
fatal: clone of 'git@github.com:braitsch/ofxSmartFont.git' into submodule path 'modules/ofxSmartFont' failed
Failed to recurse into submodule path 'third-party/ofxParagraph'
```

Probably due to a change in git reference for the 3rd part module.
However as a workaround the missing module can be cloned manually from:
https://github.com/braitsch/ofxSmartFont.git

**Comment by nebgnahz** [comment]
Mmm, that comes from ofxParagraph repository: https://github.com/braitsch/ofxParagraph/blob/master/.gitmodules#L3

To use `git clone git@github.com:XXXX`, one needs to setup the ssh key properly. Otherwise, the workaround you mentioned can work.

Closing this as not a fix-able issue from our side.
