### ISSUE TITLE
ofxGui buttons look like checkboxes, not buttons.

### ISSUE THREAD

**Issue by damellis** [damellis/ESP#80]
Which suggest you should check them to select an option, then click a separate button to actually trigger that option.

**Comment by nebgnahz** [comment]
I propose to use [DatGui](https://braitsch.github.io/ofxDatGui/index.html) for future UI improvements for openframeworks.

**Comment by nebgnahz** [comment]
Done with https://github.com/damellis/ESP/commit/a451521231ee6af5dba14fbbbad8316c6eef3129.
